name: cleaning_house
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  easy_localization: ^3.0.3
  convex_bottom_bar: ^3.2.0
  iconsax: ^0.0.8
  dio: ^5.3.3
  shared_preferences: ^2.2.2
  carousel_slider: ^4.2.1
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  flutter_screenutil: ^5.9.0
  provider: ^6.1.1
  zoom_tap_animation: ^1.1.0
  mask_text_input_formatter: ^2.5.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/png/
    - assets/svg/
    - assets/translations/


  fonts:
     - family: Inter
       fonts:
         - asset: assets/fonts/Inter-Black.ttf
         - asset: assets/fonts/Inter-Bold.ttf
         - asset: assets/fonts/Inter-Light.ttf
         - asset: assets/fonts/Inter-Medium.ttf
         - asset: assets/fonts/Inter-Regular.ttf
         - asset: assets/fonts/Inter-Thin.ttf




